version: 2.1
orbs:
  node: 'circleci/node@4.0.0'
jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  version: 2
  test_hasura_configuration:
    jobs:
      - test
