version: 2.1
orbs:
  node: 'circleci/node@4.0.0'
jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test 
workflows:
  version: 2
  configuration_check:
    jobs:
      - test
  nightly_configuration_check:
    triggers:
      - schedule:
          cron: "0 0 12 1/1 * ? *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
